//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Management.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class internshipManagementEntities : DbContext
    {
        public internshipManagementEntities()
            : base("name=internshipManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Akademisyenler> TBL_Akademisyenler { get; set; }
        public virtual DbSet<TBL_Bolumler> TBL_Bolumler { get; set; }
        public virtual DbSet<TBL_Dosyalar> TBL_Dosyalar { get; set; }
        public virtual DbSet<TBL_Fakulteler> TBL_Fakulteler { get; set; }
        public virtual DbSet<TBL_Ogrenciler> TBL_Ogrenciler { get; set; }
        public virtual DbSet<TBL_StajTurleri> TBL_StajTurleri { get; set; }
        public virtual DbSet<TBL_Bildirimler> TBL_Bildirimler { get; set; }
    }
}
