//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Management.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Ogrenciler()
        {
            this.TBL_Dosyalar = new HashSet<TBL_Dosyalar>();
            this.TBL_Bildirimler = new HashSet<TBL_Bildirimler>();
        }
    
        public int ogrenciID { get; set; }
        public string ogrenciAdi { get; set; }
        public string ogrenciSoyadi { get; set; }
        public string ogrenciNo { get; set; }
        public Nullable<byte> ogrenciFakulte { get; set; }
        public Nullable<int> ogrenciBolum { get; set; }
        public string ogrenciTelefon { get; set; }
        public string ogrenciMail { get; set; }
        public string ogrenciSifre { get; set; }
    
        public virtual TBL_Bolumler TBL_Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Dosyalar> TBL_Dosyalar { get; set; }
        public virtual TBL_Fakulteler TBL_Fakulteler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Bildirimler> TBL_Bildirimler { get; set; }
    }
}
