//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Management.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Akademisyenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Akademisyenler()
        {
            this.TBL_Dosyalar = new HashSet<TBL_Dosyalar>();
            this.TBL_Bildirimler = new HashSet<TBL_Bildirimler>();
        }
    
        public int akaID { get; set; }
        public string akaAdi { get; set; }
        public string akaSoyadi { get; set; }
        public string akaMail { get; set; }
        public string akaTelefon { get; set; }
        public Nullable<byte> akaFakulte { get; set; }
        public Nullable<int> akaBolum { get; set; }
        public Nullable<byte> akaStajTuru { get; set; }
        public string akaSifre { get; set; }
    
        public virtual TBL_Bolumler TBL_Bolumler { get; set; }
        public virtual TBL_Fakulteler TBL_Fakulteler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Dosyalar> TBL_Dosyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Bildirimler> TBL_Bildirimler { get; set; }
    }
}
